### PR TITLE
Update to new common

### PR DESCRIPTION
**Pull request by niklasva82**
Set common to zetkin/zetkin-common#63

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
The map is not showing up for me in the campaign/event sign-up form.

image

I looked in the DOM inspector and the elements are there, but the relevant one has zero height (nominally `50%`, but probably in a zero-height container). If I give it a static height the map shows up, so this seems to be a styling issue, not a javascript issue.

**Comment by niklasva82** [comment]
Bah I will look into it

**Comment by niklasva82** [comment]
Fixed the issue and made sure it works on call as well.
image

**Review by richardolsson — APPROVED** [review]
The fix does not work as the old maps did, but it's good enough to merge given the time constraints and we can improve (or replace) this in the future.

**Pull request merged**
