### PR TITLE
Feature/phone widget

### LINKED ISSUE #260: Dedicated phone widget
Create (or reuse) a mobile phone number widget with country code support to be used in the registration form.

### PR DESCRIPTION
**Pull request by niklasva82**
Resolves #260

### CODE REVIEW

**Review by richardolsson — COMMENTED** [review]
This will be a great improvement, but I think we're not quite there yet.

I have only taken a quick look at the code, but I tried the interface and have a few issues that I think we should discuss before we go into code review.

I'm commenting here on www because I think a large portion of these issues are bigger than just the widget in common, although some issues should probably be handled there.

What are your thoughts on this, @niklasva82?

## UI/visuals
I like how it's inspired by the design that is used in the other (plain) text widgets, but I don't like how it fails to line up with them on the left hand side. I think it would look nicer to have all the input box borders be in line with each other, which could be achieved by moving the flag/country select into the border, e.g. like so (quick mock in Photoshop):

image

Another issue with the design is that the country list doesn't have an outline, shadow or anything else that makes it pop out of the surrounding elements when open. This means the content is just cut off without any clear indication why. See attached screenshot of the cut-off lines.

image

## UX
I have a few comments on UX:

* I like how the four countries that correspond to Zetkin languages are at the top. Is that hardcoded or will it update automatically if we add more languages? Either is fine, just that if it's manual we need to help each other remember.
* I also like how the form pre-selects a country when on an organization page.
* I never liked how the widget just ignores zeros as first characters. How do other widgets handle this? If the user types an initial zero, we know that they have misunderstood how this widget works, and we should probably deal with it instead of just ignoring the zero.
* Tabbing does not seem to work as expected. Tabbing from the _Last Name_ field opens the country select, and I can't tab away from it. I think tabbing should skip the select entirely. Users who tab through fields probably prefer typing their number over picking from a list anyway.
* On mobile (I've only tried the simulator) it seems likely that the select list opens below the bottom edge of the screen, without the user realizing that this has happened. For mobile I think the select list should be fixed to the screen and on top of everything else.
* The current country selection is not reflected in list UI or scroll state. Pick a country (by typing or from the list) and then open the list again. It will not be scrolled to the selected country (but instead scroll state is kept from when it was last open) and the selected country is not indicated as such in the list in any way.

## Does it solve the issue?
The most important question I believe is whether this actually solves the issue we've been having, which is that users are very likely to just type their number as 0701234567, submit the form without looking very closely and receive an error message that doesn't explain very well what's wrong.

This change is a step in the right direction, because typing in 0701234567 (which just like before will actually enter as +701234567) will now show the Russian flag which will hopefully alert users that something is wrong. But it's still completely possible to make this mistake and the Russian flag may not be recognized as an error.

I think to really solve the underlying issue, we should do a few different things:

### Validation
Validate the phone number, i.e. verify that it is a valid phone number. The +701234567 number is probably not a valid number, so we should be able to catch this.

The Google library for phonenumber parsing is great for this, but it might be a little too big to include on the client-side. We could create a small endpoint on the www back-end (e.g. www.zetk.in/api/validate_phonenumber) to perform the validation on blur, and alert the user somehow if the phone number does not seem valid.

### Error messages
It would be great if the error that comes back from the API would contain adequate information to be able to alert the user that it's the phone number that is causing issues. If not, we could at least mention in the error message to the user that a common mistake is not properly including the country code.

**Comment by niklasva82** [comment]
Working on the UI and UX fixes.

Regarding the zero, where there is a default country, we could simply swap any leading zero for the default country code. This is already done when the country code is pre-entered and the user attempts to replace the country code. If we want to go further we could use IP geolocation to check for the country of the user on the global page and do the same there.

Regarding validation, it seems there is a stripped version of the Google phone number parsing library at only 130KB including metadata, referenced by the official implementation, so we could use that client-side without adding too much heft. catamphetamine/libphonenumber-js

**Comment by richardolsson** [comment]
> Regarding the zero, where there is a default country, we could simply swap any leading zero for the default country code.

I think this sounds like a good solution!

> This is already done when the country code is pre-entered and the user attempts to replace the country code.

Are you sure? If I delete the pre-entered code on an organization page and type 070…, it works the same as on the home page. Steps to reproduce:

1. Navigate to www.dev.zetkin.org/o/1 (where default country code is +46)
2. Focus the e-mail field to open registration form
3. Place cursor/caret at end of pre-entered country prefix
4. Press backspace three times to delete "everything" (+ sign remains, as intended)
5. Type 070

Expected result (based on my understanding of what you're saying above): The zero should be immediately replaced with +46
Actual result: The zero is dropped and the entered number is "70", which is interpreted as the beginning of a Russian number, and the Russian flag is displayed.

The same happens when I try some other ways of deleting the pre-entered prefix (steps 3 and 4), e.g. selecting and hitting backspace or selecting and typing over it.

> If we want to go further we could use IP geolocation to check for the country of the user on the global page and do the same there.

Let's not go that far for this update, but I think it's something we could consider down the line if we see that this doesn't fix the problem.

> Regarding validation, it seems there is a stripped version of the Google phone number parsing library at only 130KB including metadata, referenced by the official implementation, so we could use that client-side without adding too much heft. https://github.com/catamphetamine/libphonenumber-js

Interesting! That's still a lot just for phone number validation, but maybe it's worth a try. The next challenge though is how we actually indicate when something is wrong. Red border? Red x icon to the right of field? Something else?

If you want to give it a try I think that would be great! But I think the most important piece to the puzzle is dealing with the zero when on an organization page, which is where most people register anyway.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Thanks for making the updates. UX is much better now!

I still found an issue with this, which is that the visual state does not seem to reflect pre-filled values (e.g. after submitting the form and getting an error).

Here are steps to reproduce:
1. Navigate to home page
2. Fill out registration form, but use an invalid Swedish number, e.g. +467012345
3. Submit the form, which will come back with an error message and re-render the form

Expected result: Phone field should display Swedish flag and red border because of the invalid number
Actual result: Phone field displays incorrect number, but "international" flag and regular border (screenshot below).

image

**Comment by richardolsson** [comment]
Wrongly closed by incorrect reference in zetkin/zetkin-common#50. Re-opening to merge.

**Review by richardolsson — APPROVED** [review]
LGTM!

**Pull request merged**
