### PR TITLE
Require user phone to be in E164 format when registering

### PR DESCRIPTION
**Pull request by stefanfisk**
Resolves https://github.com/zetkin/www.zetk.in/issues/255.

The existing components I looked at for phone number input  at where either super heavy or kinda weird, so I hacked together some value wrangling that should make it clear which format is expected.

Might it also make sense to mark the required fields somehow? Currently there's no way to tell that the phone number is not required.

### CODE REVIEW

**Comment by stefanfisk** [comment]
Now that I think of it, this might be super confusing for users with js turned off (which I noticed you want to support). There's no indication that the format must be international. I can't think of a nice solution off the top of my head, how much do you cater to those users? The form should still work, there's just no feedback on why the submit fails.

**Comment by richardolsson** [comment]
There should be feedback on why the submit fails (400), even if it's just a general "make sure all the fields are filled in correctly" and a placeholder which includes the +. Does that make sense?

**Comment by stefanfisk** [comment]
The placeholders are not styled to be visible, and are part of the initial animation, so using them would be quite a bit of work since I'm not very familiar with the code.

But, I am now prefilling the field with '+' for non-JS visitors, which I reckon should be enough.

Please do test the JS UX though. I like it, but I might be a freak user :)

**Comment by stefanfisk** [comment]
Sorry about that, it was a last second addition that I obviously didn't test as needed. Now it's doing what it should.

**Comment by richardolsson** [comment]
Thanks! I will look at this tomorrow, hopefully it's not a blocker for you?

Please try to refrain from overwriting commits and force-pushing when fixing bugs. It makes it very difficult in retrospect to understand what the issue was, which may impede future detective work.

**Comment by stefanfisk** [comment]
Just force pushed to restore the commit I had amended, and instead added new commits for the changes I had made.

**Pull request merged**
