### PR TITLE
Redesign landing page Sign up splash

### PR DESCRIPTION
**Pull request by jensborje**
screen shot 2018-07-17 at 17 06 36
screen shot 2018-07-17 at 17 10 34
screen shot 2018-07-17 at 17 06 25
screen shot 2018-07-17 at 17 06 58
screen shot 2018-07-17 at 17 09 40

### CODE REVIEW

**Comment by richardolsson** [comment]
This is looking amazing! I know you're still working on this, so these points might be redundant, but here are some things that I noticed:

1. Error messages do not seem to be working. Try signing up using testuser@example.com which is already registered, ur using a phone number that is not a phone number.
2. We talked about having some sort of leading paragraph under the header, before the form, to explain the process of, and reason for, signing up.
3. Logo is kinda difficult to make out on mobile. We talked about using some sort of gradient shader. I think that could work, even at 10% or so.
4. After registering, the message explaining the next step (check your inbox) seems to be fixed at the bottom of the area. I think it should be more front and center.

Again, this is great work!

**Comment by jensborje** [comment]
Thanks, and great with feedback. Regarding no 1, I think this is solved all ready.
screen shot 2018-07-17 at 07 45 46

I will see what I can do regarding the other points!

**Comment by richardolsson** [comment]
Re 1: The error message in your screenshot is for when required fields are missing. Try registering with a user that already exists. This is what I get.

image

**Comment by richardolsson** [comment]
Trying to register an e-mail that is already registered should ideally display some sort of login CTA. Maybe add a link to the error message. Just use a regular `<a href="/dashboard">`, and that will trigger a login redirect.

**Comment by jensborje** [comment]
Seems like I get an error 400 no matter what I enter. 409 is not triggered.

screen shot 2018-07-17 at 08 05 49

**Comment by jensborje** [comment]
Killed and restarted on my machine and now I get a 409 as well. I'll try to fix a login CTA as you proposed.

screen shot 2018-07-17 at 08 17 56

**Comment by jensborje** [comment]
Made a couple of tweaks today. If I haven't missed anything, I would consider this as done now.

Left to to is adding correct strings for the localization. Leaving this to @richardolsson to do as you please.

**Comment by richardolsson** [comment]
This is looking great. I've found some issues though, but will merge and create a new pull request where I can fix them, so that you can easily review those changes in isolation.

**Pull request merged**
