### PR TITLE
Recommended organizations

### PR DESCRIPTION
**Pull request by richardolsson**
This PR adds a "recommended organizations" section in the `Welcome` component. It relies on a new feature in the API and cannot be tested live until the next version.

image

### CODE REVIEW

**Comment by richardolsson** [comment]
This is what it looks like when Zetkin can't recommend any organization. 
image

**Comment by richardolsson** [comment]
And this is what it looks like on a small screen. 
image

**Comment by richardolsson** [comment]
Would love your feedback (and potential help) on the design of this, @jensborje. Lets talk offline today.

**Comment by jensborje** [comment]
Here's some design!

screen shot 2018-05-28 at 10 16 38
screen shot 2018-05-28 at 10 16 55

Demo:
https://sketch.cloud/s/APzO4

**Pull request merged**
